version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
